"""
Provenance Guard - AI Detection Service
services/detector.py: Calls the Groq API to classify text as AI-generated or human-written.
"""

import json
import os

from dotenv import load_dotenv
from groq import Groq

# Load environment variables from .env (must contain GROQ_API_KEY)
load_dotenv()

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = """\
You are an expert forensic linguist specialising in detecting AI-generated text.
Analyse the text supplied by the user and decide whether it was written by a human
or generated by an AI system.

Respond with ONLY a valid JSON object — no explanation, no markdown, no code fences.
The object must have exactly these two keys:

  "classification": one of "likely_ai", "likely_human", or "uncertain"
  "score": a float in [0.0, 1.0] representing your confidence that the text is AI-generated
           (1.0 = certainly AI, 0.0 = certainly human)

Example output:
{"classification": "likely_ai", "score": 0.86}
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def analyze_text(text: str) -> dict:
    """
    Analyse *text* and return a classification dict.

    Args:
        text: The raw string to evaluate.

    Returns:
        A dict with keys:
            - "classification" (str): "likely_ai" | "likely_human" | "uncertain"
            - "score"          (float): confidence that the text is AI-generated [0, 1]

    Raises:
        ValueError: If the model returns a response that cannot be parsed or is
                    structurally invalid.
        RuntimeError: If the Groq API call itself fails.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise RuntimeError(
            "GROQ_API_KEY is not set. "
            "Add it to your .env file or export it as an environment variable."
        )

    client = Groq(api_key=api_key)

    try:
        response = client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user",   "content": text},
            ],
            temperature=0.0,   # deterministic output for consistent JSON
            max_tokens=64,     # the response is tiny; cap tokens to save quota
        )
    except Exception as exc:
        raise RuntimeError(f"Groq API request failed: {exc}") from exc

    raw = response.choices[0].message.content.strip()

    # Parse and validate the returned JSON
    try:
        result = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"Model returned non-JSON content: {raw!r}"
        ) from exc

    _validate_result(result)
    return result


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

VALID_CLASSIFICATIONS = {"likely_ai", "likely_human", "uncertain"}


def _validate_result(result: dict) -> None:
    """Raise ValueError if *result* does not match the expected schema."""
    if not isinstance(result, dict):
        raise ValueError(f"Expected a JSON object, got: {type(result).__name__}")

    missing = {"classification", "score"} - result.keys()
    if missing:
        raise ValueError(f"Response JSON is missing required key(s): {missing}")

    if result["classification"] not in VALID_CLASSIFICATIONS:
        raise ValueError(
            f"Invalid classification {result['classification']!r}. "
            f"Must be one of {VALID_CLASSIFICATIONS}."
        )

    if not isinstance(result["score"], (int, float)) or not (0.0 <= result["score"] <= 1.0):
        raise ValueError(
            f"'score' must be a float in [0, 1], got: {result['score']!r}"
        )


# ---------------------------------------------------------------------------
# Quick smoke-test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    SAMPLE_AI_TEXT = (
        "The implementation of machine learning algorithms necessitates a "
        "comprehensive understanding of both theoretical foundations and "
        "practical considerations, ensuring optimal performance across diverse "
        "datasets and computational environments."
    )

    SAMPLE_HUMAN_TEXT = (
        "I honestly had no idea what I was doing when I started this project. "
        "I just kind of winged it and hoped for the best — turns out that works "
        "sometimes, at least a little bit."
    )

    for label, sample in (("AI-like text", SAMPLE_AI_TEXT), ("Human-like text", SAMPLE_HUMAN_TEXT)):
        print(f"\n--- {label} ---")
        print(f"Input : {sample[:80]}...")
        try:
            output = analyze_text(sample)
            print(f"Result: {output}")
        except (ValueError, RuntimeError) as err:
            print(f"Error : {err}")
